# Generated by Django 4.1.6 on 2023-03-03 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TVParser',
            new_name='CarParser',
        ),
    ]
