# Generated by Django 4.1.6 on 2023-03-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_rename_tvparser_carparser'),
    ]

    operations = [
        migrations.AddField(
            model_name='carparser',
            name='info',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carparser',
            name='price',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
