# Generated by Django 4.1.6 on 2023-02-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows', '0002_tvshow_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvshow',
            name='quatity',
        ),
        migrations.AddField(
            model_name='tvshow',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='quantity',
            field=models.PositiveIntegerField(null=True, verbose_name='Колличество фильмов'),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='video',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание фильма'),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='genre',
            field=models.CharField(choices=[('HORROR', 'HORROR'), ('COMEDY', 'COMEDY'), ('FANTASY', 'FANTASY'), ('THRILLER', 'THRILLER'), ('MELODRAMME', 'MELODRAMME')], max_length=100, null=True),
        ),
    ]
