# Generated by Django 4.1.6 on 2023-02-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows', '0004_ratingtv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingtv',
            name='rate',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
