# Generated by Django 4.1.6 on 2023-02-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='genre',
            field=models.CharField(choices=[('NEWS', 'NEWS'), ('OLD', 'OLD')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='quantity',
            field=models.PositiveIntegerField(null=True, verbose_name='Колличество статей в посте'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(null=True, verbose_name='Дополнитенльное описание поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='Название поста'),
        ),
    ]
