# Generated by Django 4.1.6 on 2023-02-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('AUTOBIOGRAPHY', 'AUTOBIOGRAPHY'), ('SPEECH', 'SPEECH'), ('ESSAY', 'ESSAY'), ('BIOGRAPHY', 'BIOGRAPHY'), ('DIARY', 'DIARY')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.PositiveIntegerField(null=True, verbose_name='Колличество книг'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='Название книги'),
        ),
    ]
