# Generated by Django 4.1.6 on 2023-02-28 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_genre_book_quantity_alter_book_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], verbose_name='Оценка: ')),
                ('comment', models.TextField(verbose_name='Комментарий: ')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('choice_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_object', to='book.book')),
            ],
        ),
    ]
